import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
// import LoginPage from './auth/login';
import DoctorTable from '@/components/Table/DoctorTable';
import { Space, Typography } from 'antd';
import BreadCrumb from '@/components/BreadCrumb';
import CaseCard from '@/components/Card/CasesCard';
import DateSearchFilters from '@/components/DateSearchFilter';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Cases</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <Typography.Title
          level={1}
          style={{
            margin: 0,
            textAlign: 'left',
          }}
        >
          Cases
        </Typography.Title> */}
        {/* <BreadCrumb /> */}
        <DateSearchFilters placeholder="Search cases" />
        {/* <DoctorTable data={data} columns={columns} /> */}
        <div className="flex">
          <CaseCard
            age="Age: 12"
            name="Fluffy"
            breed="German Shepherd"
            image="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSj5DTy38Tn--8rMY2LI3rpzV0_nQI1iHuKdw&usqp=CAU"
            disease="Predicted Disease: Ringworm"
            // heatMap="https://media.istockphoto.com/id/860248068/photo/beautiful-mutt-black-dog-on-mountain-rock.jpg?s=2048x2048&w=is&k=20&c=K09MP1b8wYgwmi2ZcmjMN_LQ6nIJlU4uhw6GmOxKnKo="
          />
          <CaseCard
            age="Age: 14"
            name="Alex"
            breed="Golden Retriever"
            image="https://www.thesprucepets.com/thmb/baW88YsVO_JqNBNJPhCFBHbNUMM=/1500x0/filters:no_upscale():strip_icc()/dog-breed-profile-golden-retriever-1117969-hero-da398f6462704058ace0ef5ae007866d.jpeg"
            disease="Predicted Disease: Mange"
            // heatMap="https://media.istockphoto.com/id/860248068/photo/beautiful-mutt-black-dog-on-mountain-rock.jpg?s=2048x2048&w=is&k=20&c=K09MP1b8wYgwmi2ZcmjMN_LQ6nIJlU4uhw6GmOxKnKo="
          />
          <CaseCard
            age="Age: 18"
            name="Browny"
            breed="Bulldog"
            image="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXY7AhKVWZDEX3esy5Ia8TzNxcoG3o1xHEHg&usqp=CAU"
            disease="Predicted Disease: Ringworm"
            // heatMap="https://media.istockphoto.com/id/860248068/photo/beautiful-mutt-black-dog-on-mountain-rock.jpg?s=2048x2048&w=is&k=20&c=K09MP1b8wYgwmi2ZcmjMN_LQ6nIJlU4uhw6GmOxKnKo="
          />
        </div>
      </main>
    </>
  );
}
